version: 2
jobs:
  build:
    docker:
      - image: apility/docker
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: ./release.sh

workflows:
  version: 2
  build-image:
    jobs:
      - build:
          context: Docker
